//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFEA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    
    public partial class le_bien
    {
        public int id_bien { get; set; }
        public string type_bien { get; set; }
        public string superficie { get; set; }
        public string description { get; set; }
        public string localisation { get; set; }
        public decimal prix { get; set; }
        public string image { get; set; }
        public HttpPostedFileBase File { get; set; }
        public Nullable<System.DateTime> date_annonces { get; set; }
    }
}
